### ISSUE TITLE
Cannot import module?

### ISSUE THREAD

**Issue by RSKothari** [elerac/structuredlight#3]
```
pip install git+https://github.com/elerac/structuredlight --user
Collecting git+https://github.com/elerac/structuredlight
  Cloning https://github.com/elerac/structuredlight to /tmp/pip-req-build-0uxavpp5
  Running command git clone -q https://github.com/elerac/structuredlight /tmp/pip-req-build-0uxavpp5
Requirement already satisfied (use --upgrade to upgrade): structuredlight==1.0.1 from git+https://github.com/elerac/structuredlight in /usr/local/lib/python3.5/dist-packages
Building wheels for collected packages: structuredlight
  Building wheel for structuredlight (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-tulcnpfd/wheels/50/aa/93/875360f299ad1d3427d286178f48cbe0ed46c858aa0a6c32e0
Successfully built structuredlight
```

```ModuleNotFoundError: No module named 'structuredlight'```

**Comment by elerac** [comment]
Hi @RSKothari !

As you show me, `structuredlight` is successfully built. So, it seems that you need to **revise your python or pip environment settings** to solve this problem. Is it possible to install and import other modules (e.g., numpy, matplotlib, scipy, ...etc.) with **your pip**?

A common mistake is that the pip and the python environment are different.
Do you have both python2 and python3? (then, try `pip3` once) Do you have multiple pythons? If so, you may need to revise your environment settings.

If it turns out that it is not an environmental problem, please let me know. I think this is unlikely, but this program may contain a problem.
